# Generated by Django 5.1.4 on 2025-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('academic_year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
